### ISSUE TITLE
AKS Learn feedback: typo (nodepool name mismatch)

### ISSUE THREAD

**Issue by torumakabe** [MicrosoftDocs/azure-aks-docs#100]
### Type of issue

Typo

### Feedback

There is a mismatch in the content of ["Add a manual scale profile to a node pool"](https://learn.microsoft.com/en-us/azure/aks/virtual-machines-node-pools#add-a-manual-scale-profile-to-a-node-pool) section.

In the text, the node pool name is "myvmpool," but in the command, it is "myvmpool1."

It's a minor difference that can be noticed upon careful reading, but it caused confusion at first glance. I would appreciate it if you could make the correction.

### Page URL

https://learn.microsoft.com/en-us/azure/aks/virtual-machines-node-pools

### Content source URL

https://github.com/MicrosoftDocs/azure-aks-docs/blob/main/articles/aks/virtual-machines-node-pools.md

### Author

@wdarko1

### Document Id

5b8d05eb-273f-e369-a3f5-4c739008b3e3

**Comment by schaffererin** [comment]
#reassign:schaffererin

**Comment by schaffererin** [comment]
Hi, @torumakabe. Thank you for your feedback!

I've merged a [PR](https://github.com/MicrosoftDocs/azure-aks-docs-pr/pull/599) that addresses this issue, and the changes will be live in the AKS documentation shortly.

I will now close out this issue. Thanks again :)

#please-close
