### ISSUE TITLE
AKS Learn feedback: Incorrect or Missing Information in AKS Quickstart Documentation

### ISSUE THREAD

**Issue by Latzox** [MicrosoftDocs/azure-aks-docs#102]
### Type of issue

Missing information

### Feedback

The documentation does not fully explain the additional resource groups created when deploying an AKS cluster using the New-AzAksCluster command. This omission can lead to confusion when users try to clean up resources after completing the quickstart tutorial.

**Detailed Description:**
When deploying an AKS cluster with the New-AzAksCluster command, two additional resource groups are automatically created:

- Network Watcher Resource Group: This is created for monitoring purposes in the region where the virtual network resides.
- Managed Cluster Resource Group: This resource group contains all the infrastructure components required for the AKS cluster, such as Virtual Machine Scale Sets, Load Balancers, and Public IP addresses. The naming convention for this resource group follows the pattern: `MC_<ResourceGroupName>_<AKSClusterName>_<Region>`

**The documentation should:**

- Include details about these additional resource groups and their purpose.
- Clarify that users must delete these resource groups to fully clean up after testing AKS.

**Suggested Update to Documentation:**
Update the "Delete the cluster" section to include a note about these additional resource groups and their cleanup process. For example:

```
In addition to the main resource group, the deployment creates two additional resource groups:

- A Network Watcher resource group (used for monitoring).
- A Managed Cluster resource group containing AKS infrastructure resources. Ensure you delete these additional resource groups to avoid ongoing Azure charges.
```

Provide an example command to delete the managed cluster resource group:

```
Remove-AzResourceGroup -Name MC_myResourceGroup_myAKSCluster_westus
```

**Why This Matters:**
Leaving these additional resource groups undeleted can result in unexpected Azure charges. Including this information will improve the overall accuracy of the documentation and help users better manage their Azure resources.

Thank you for considering this feedback. Let me know if further clarification is needed!

### Page URL

https://learn.microsoft.com/en-us/azure/aks/learn/quick-kubernetes-deploy-powershell

### Content source URL

https://github.com/MicrosoftDocs/azure-aks-docs/blob/main/articles/aks/learn/quick-kubernetes-deploy-powershell.md

### Author

@tamram

### Document Id

c71f4c52-7711-69d4-36a1-c43bd140b15d

**Comment by schaffererin** [comment]
#reassign:schaffererin

**Comment by schaffererin** [comment]
hi, @Latzox. thank you for your feedback. i updated the callout about the second resource group. the [pr](https://github.com/MicrosoftDocs/azure-aks-docs-pr/pull/671) was merged, and the updated article will be live shortly. i will now close out this github issue. thanks again!

#please-close
