### ISSUE TITLE
AKS Learn feedback: we should reminder customer pay attention of azure disk zone limit when resize nodepool 

### ISSUE THREAD

**Issue by tfbubu111** [MicrosoftDocs/azure-aks-docs#106]
### Type of issue

Missing information

### Feedback

Hi team, 

During nodepool resize, if customer has azure disk in use. We should mention that the new nodepool needs to be same availability zone as old nodepool. Incase azure disk cannot be mounted to new node:

For example, previous node is created in eastus2 az01. but new nodepool is created without zone selection. 
" 2 node(s) had volume node affinity conflict. preemption: 0/2 nodes are available: 2 Preemption is not helpful for scheduling."

### Page URL

https://learn.microsoft.com/en-us/azure/aks/resize-node-pool?tabs=azure-cli

### Content source URL

https://github.com/MicrosoftDocs/azure-aks-docs/blob/main/articles/aks/resize-node-pool.md

### Author

@schaffererin

### Document Id

8f3a2dfe-0619-3b4b-aa96-6a9f5938d690

**Comment by schaffererin** [comment]
#assign:schaffererin
