### ISSUE TITLE
AKS Learn feedback:

### ISSUE THREAD

**Issue by john-a-joyce** [MicrosoftDocs/azure-aks-docs#112]
### Type of issue

Other (describe below)

### Feedback

The steps did not all work for me.  Note I am using a trial subscription and just started walking through the tutorials with no other pre setup.   Specifically, the build command from the "Create an Azure container page" failed see below.   Note that I code build locally with docker compose and could push to my ACR with docker push.   
--------- 
 az acr build --registry $ACRNAME --image aks-store-demo/product-service:latest ./src/product-service/
Packing source code into tar to upload...
Excluding '.gitignore' based on default ignore rules
Uploading archived source code from '/tmp/build_archive_1c8b6a1739b44cc2bb34660aa6a3ea40.tar.gz'...
Sending context (1022.404 KiB) to registry: johnajoyce17...
(TasksOperationsNotAllowed) ACR Tasks requests for the registry johnajoyce17 and 855bbbaa-a548-4102-8a50-01b33ced20af are not permitted. Please file an Azure support request at http://aka.ms/azuresupport for assistance.
Code: TasksOperationsNotAllowed
Message: ACR Tasks requests for the registry johnajoyce17 and 855bbbaa-a548-4102-8a50-01b33ced20af are not permitted. Please file an Azure support request at http://aka.ms/azuresupport for assistance.
Target: request
-----------------------------------------------------------------------------------------------------------------

### Page URL

https://learn.microsoft.com/en-us/azure/aks/tutorial-kubernetes-prepare-acr?tabs=azure-cli

### Content source URL

https://github.com/MicrosoftDocs/azure-aks-docs/blob/main/articles/aks/tutorial-kubernetes-prepare-acr.md

### Author

@schaffererin

### Document Id

e0ace6aa-4b2e-d840-a6fe-cc521faba04d

**Comment by schaffererin** [comment]
#assign:schaffererin

**Comment by schaffererin** [comment]
Hi @john-a-joyce, it seems like this is not an issue with the documentation, but something to do with your Azure subscription. Please file the Azure support request using the link shared. I'm going to go ahead and close out this GitHub issue, as it isn't related to any issues with the documentation itself. Thank you! #please-close
