### ISSUE TITLE
AKS Learn feedback: api-server-authorized-ip-ranges is not functional with service tags

### ISSUE THREAD

**Issue by Shawn-StatRecovery** [MicrosoftDocs/azure-aks-docs#120]
### Type of issue

Code doesn't work

### Feedback

Executing the AKS creation command

`az aks create --resource-group myResourceGroup --name myAKSCluster --api-server-authorized-ip-ranges AzureCloud,20.20.20.20`

results in an exception:

`--api-server-authorized-ip-ranges should be a list of IPv4 addresses or CIDRs`

### Page URL

[Create an AKS cluster with Service Tag authorized IP ranges](https://learn.microsoft.com/en-us/azure/aks/api-server-authorized-ip-ranges?tabs=azure-cli#create-an-aks-cluster-with-service-tag-authorized-ip-ranges)

### Content source URL

[Create an AKS cluster with Service Tag authorized IP ranges
](https://learn.microsoft.com/en-us/azure/aks/api-server-authorized-ip-ranges?tabs=azure-cli#create-an-aks-cluster-with-service-tag-authorized-ip-ranges)

### Author

@schaffererin

### Document Id

b3124556-4672-d2aa-aab1-64d2cd3ac354

**Comment by schaffererin** [comment]
hi, @Shawn-StatRecovery! thank you for your feedback. i've just run through the commands with no issues. i didn't receive any exception messages. we've identified no issues with the documentation itself, so i'm going to go ahead and close out this issue. 

i'd recommend retrying the steps, making sure you [install the preview extension](https://learn.microsoft.com/azure/aks/api-server-authorized-ip-ranges?tabs=azure-cli#install-the-azure-cli-preview-extension) and [register the service tag feature flag](https://learn.microsoft.com/azure/aks/api-server-authorized-ip-ranges?tabs=azure-cli#register-the-service-tag-authorized-ip-feature-flag).

thanks again! #please-close

**Comment by Shawn-StatRecovery** [comment]
Thank you @schaffererin
