### ISSUE TITLE
AKS Learn feedback: multiple items in TOC pointing to same document

### ISSUE THREAD

**Issue by JoeyC-Dev** [MicrosoftDocs/azure-aks-docs#13]
### Type of issue

Other (describe below)

### Feedback

The below two items in TOC are pointing to the same document:
![image](https://github.com/user-attachments/assets/9dd6efed-35ed-4d37-9933-a4df6e2a0b08)

### Page URL

https://learn.microsoft.com/en-us/azure/aks/availability-zones

### Content source URL

https://github.com/MicrosoftDocs/azure-aks-docs/blob/main/articles/aks/availability-zones.md

### Author

@schaffererin

### Document Id

10de5ee1-942d-e30f-5f0c-f163bd45904d

**Comment by schaffererin** [comment]
#assign:schaffererin

**Comment by schaffererin** [comment]
@JoeyC-Dev, thank you again for your contribution to the AKS documentation. I created and signed off on a [PR](https://github.com/MicrosoftDocs/azure-aks-docs-pr/pull/66) to fix this issue. The PR will be merged shortly, so I'm going to close out this GitHub issue.

#please-close
