### ISSUE TITLE
AKS Learn feedback:

### ISSUE THREAD

**Issue by bbstricker** [MicrosoftDocs/azure-aks-docs#14]
### Type of issue

Missing information

### Feedback

The document is missing directives to make sure a "target port" be specified, and that the "app selector" be changed to users app.
This would be helpful for the when trying to use an Internal LB for the AKS cluster:
Ref: https://kubernetes.io/docs/concepts/services-networking/service/#loadbalancer

### Page URL

https://learn.microsoft.com/en-us/azure/aks/internal-lb?tabs=set-service-annotations

### Content source URL

https://github.com/MicrosoftDocs/azure-aks-docs/blob/main/articles/aks/internal-lb.md

### Author

@asudbring

### Document Id

7629191a-6b3b-fb22-8b70-fa84fd785f38

**Comment by asudbring** [comment]
@bbstricker 
The article referenced says those are for an external load balancer.  This article is for an internal load balancer and doesn't need the target port.  I will consult with my PM for sure and update if needed.

Thanks!
#please-close
