### ISSUE TITLE
AKS Learn feedback: Documentation should reference the cloud provider docs to understand annotations available when configuring a service

### ISSUE THREAD

**Issue by ivanthelad** [MicrosoftDocs/azure-aks-docs#18]
### Type of issue

Missing information

### Feedback

Documentation should reference the cloud provider docs to understand annotations available when configuring a service.

https://cloud-provider-azure.sigs.k8s.io/topics/loadbalancer/#loadbalancer-annotations

Currently docs only highlight annotations for particular scenarios.  as supplementary information the documentation should reference the cloudprovider documentation which has comprehensive list of annotations available 

### Page URL

https://learn.microsoft.com/en-us/azure/aks/internal-lb?tabs=set-service-annotations

### Content source URL

https://github.com/MicrosoftDocs/azure-aks-docs/blob/main/articles/aks/internal-lb.md

### Author

@asudbring

### Document Id

7629191a-6b3b-fb22-8b70-fa84fd785f38

**Comment by schaffererin** [comment]
#assign:schaffererin

**Comment by schaffererin** [comment]
Hi, @ivanthelad. Thank you for your feedback. I updated the article with a link to the cloud provider docs per your suggestion. My [PR with the changes](https://github.com/MicrosoftDocs/azure-aks-docs-pr/pull/609) has been merged, and the public-facing AKS article will be updated shortly. I'm now going to close out this GitHub issue. Thanks again!

#please-close
