### ISSUE TITLE
AKS Learn feedback: Inconsistent naming for AAD and Workload Entra ID and FICs clarification in AKS

### ISSUE THREAD

**Issue by jaellio** [MicrosoftDocs/azure-aks-docs#20]
### Type of issue

Other (describe below)

### Feedback

1. The documentation and diagrams inconsistently refer to Microsoft Entra ID and Azure Active Directory. A user might not be aware these names are equivalent, and it introduces unnecessary confusion.  

 ![image](https://github.com/user-attachments/assets/5209013f-55b0-41af-9e93-24fcf7414f60)
2. This article is linked from a page on [workload identity federation](https://learn.microsoft.com/en-us/entra/workload-id/workload-identity-federation). It would be helpful if this article could explain the use of federated identity credentials in the context of AKS. FICs are only mentioned in the limitation section and without them being explained it makes it hard to understand why FICs would be a limitation.

### Page URL

https://learn.microsoft.com/en-us/azure/aks/workload-identity-overview?tabs=dotnet

### Content source URL

https://github.com/MicrosoftDocs/azure-aks-docs/blob/main/articles/aks/workload-identity-overview.md

### Author

@tamram

### Document Id

c9dde5dc-de8a-ba8d-2330-327b0499ac81

**Comment by aramase** [comment]
@miwithro @CocoWang-wql could you please take a look and assign the owner to make edits?

**Comment by schaffererin** [comment]
#assign:schaffererin

**Comment by schaffererin** [comment]
Hi, @jaellio, thank you for your feedback. The article has been updated. I will now close out this GitHub issue. #please-close
