### ISSUE TITLE
AKS Learn feedback: already deprecated API versions

### ISSUE THREAD

**Issue by JoeyC-Dev** [MicrosoftDocs/azure-aks-docs#23]
### Type of issue

Outdated article

### Feedback

In the current version, the "upcoming deprecated" APIs are already deprecated:
![image](https://github.com/user-attachments/assets/dcadc04f-f775-43f7-ba0e-0c3a4fad92a4)

Should the document being modified since these APIs has passed the deprecation date?

### Page URL

https://learn.microsoft.com/en-us/azure/aks/concepts-preview-api-life-cycle#upcoming-deprecations

### Content source URL

https://github.com/MicrosoftDocs/azure-aks-docs/blob/main/articles/aks/concepts-preview-api-life-cycle.md

### Author

@matthchr

### Document Id

349a2ce3-7aff-b0cf-d231-0c6c2b1426db

**Comment by schaffererin** [comment]
#assign: matthchr

**Comment by schaffererin** [comment]
hi @JoeyC-Dev, thanks for your feedback here. i touched base with our internal team, and because of some various blockers, we'll need to wait to update the article until changes move through in january. we're tracking this on our end, so i'm going to close out this issue. #please-close
