### ISSUE TITLE
AKS Learn feedback: Specific node is not working and I can't remove it

### ISSUE THREAD

**Issue by Leonardo-Ferreira** [MicrosoftDocs/azure-aks-docs#3]
### Type of issue

Missing information

### Feedback

I have a node pool with 10+ nodes and now the node 000000 is not working properly and I would like it to be removed/recreated. How can I specify that? Similar to [#16721](https://github.com/MicrosoftDocs/azure-docs/issues/16721)

### Page URL

https://learn.microsoft.com/en-us/azure/aks/cluster-autoscaler?tabs=azure-cli

### Content source URL

https://github.com/MicrosoftDocs/azure-aks-docs/blob/main/articles/aks/cluster-autoscaler.md

### Author

@schaffererin

### Document Id

0fd87b4f-88a4-c2eb-3ebc-f2b113ac203c

**Comment by schaffererin** [comment]
#assign:schaffererin

**Comment by schaffererin** [comment]
Hi, @Leonardo-Ferreira!

To clarify, is this problem related to an issue with the cluster autoscaler article in particular, or is it instead just an issue with a particular node?

Are any of the following resources helpful for you?

* [AKS node auto-repair](https://learn.microsoft.com/en-us/azure/aks/node-auto-repair)
* [Troubleshoot AKS clusters or nodes in a failed state](https://learn.microsoft.com/en-us/troubleshoot/azure/azure-kubernetes/availability-performance/cluster-node-virtual-machine-failed-state)

**Comment by Leonardo-Ferreira** [comment]
The issue with the node, made me look into the documentation searching for a way to delete a specific node... I found nothing pertaining to "how to remove a specific node", only "scaling out and scaling in"... in my point of view, the documentation should have a section "Remove/Recycle/Restart/Recreate a specific node" and if that is indeed a not supported operation, that should be clearly stated

**Comment by schaffererin** [comment]
@Leonardo-Ferreira, the guidance on managing nodes isn't in the autoscaling docs. Please see https://learn.microsoft.com/azure/aks/manage-node-pools#remove-specific-vms-in-the-existing-node-pool-preview for information about removing a specific node. Since no updates are needed to the article in question, I'm going to close out this GitHub issue. Thank you! #please-close
