### ISSUE TITLE
AKS Learn feedback: `hubble relay service` command does not exist

### ISSUE THREAD

**Issue by alexcastilio** [MicrosoftDocs/azure-aks-docs#33]
### Type of issue

Code doesn't work

### Feedback

Command `hubble relay service` does not exist for hubble CLI version v0.11.0

### Page URL

https://learn.microsoft.com/en-us/azure/aks/advanced-network-observability-cli?tabs=non-cilium

### Content source URL

https://github.com/MicrosoftDocs/azure-aks-docs/blob/main/articles/aks/advanced-network-observability-cli.md

### Author

@Khushbu-Parekh

### Document Id

2b5d7421-ef48-6763-d2f1-6b2cfe5c0788

**Comment by schaffererin** [comment]
#assign:schaffererin

**Comment by schaffererin** [comment]
Hi, @alexcastilio! Thank you for your feedback. I updated the article, and the [PR ](https://github.com/MicrosoftDocs/azure-aks-docs-pr/pull/199)has been merged. The changes will be live in the doc shortly. I will now close this GitHub issue. Thanks again! #please-close
