### ISSUE TITLE
AKS Learn feedback: Unable to build the project using Azure CLI

### ISSUE THREAD

**Issue by bellons91** [MicrosoftDocs/azure-aks-docs#36]
### Type of issue

Code doesn't work

### Feedback

Once logged in, the Azure CLI references a "cloud" file system, even if the CLI is executed locally.
 
![image](https://github.com/user-attachments/assets/18af3aab-c724-4f6f-9f3f-c5325dbb2f5d)

This means that the instructions listed in the "Build and push container images to registry" section cannot be executed, since they reference the repository stored locally (as defined in the previous page), as they are stored in a different file system (cloud vs local file system)

![image](https://github.com/user-attachments/assets/bf571e5e-55a9-4b44-bfc0-c538680c667f)

### Page URL

https://learn.microsoft.com/en-us/azure/aks/tutorial-kubernetes-prepare-acr?tabs=azure-cli#build-and-push-container-images-to-registry

### Content source URL

https://github.com/MicrosoftDocs/azure-aks-docs/blob/main/articles/aks/tutorial-kubernetes-prepare-acr.md

### Author

@schaffererin

### Document Id

c67857a5-ee1b-3ed2-f281-dd62c4c4c6f3

**Comment by schaffererin** [comment]
#assign:schaffererin

**Comment by schaffererin** [comment]
Hi, @bellons91, thank you for leaving your feedback.

I tested the tutorials locally using the Azure CLI and didn't experience any issues. Based on the screenshot you shared, it appears as though you might need to `cd` into the `aks-store-demo` repository. My ask is for you to retest and ensure you've completed all the steps in https://learn.microsoft.com/en-us/azure/aks/tutorial-kubernetes-prepare-app.

It appears there are no updates required to the article for now, so I'm going to close out this GitHub issue. Please feel free to tag me if you find an issue in the documentation after retesting.

Thank you! #please-close

**Comment by bellons91** [comment]
@schaffererin , as you can see from the first screenshot, there is no "aks-store-demo" folder, since the context is different from my local environment.

Or maybe should I download the repository not locally but on the cloud shell? Was I missing that point?
