### ISSUE TITLE
AKS Learn feedback: wrong FAQ

### ISSUE THREAD

**Issue by h-akshay1** [MicrosoftDocs/azure-aks-docs#40]
### Type of issue

Typo

### Feedback

Community support for AKS 1.27 will end in July 2024. Will I be able to create new AKS clusters with version 1.27 after that date?
**Yes, you will be able to create new AKS clusters with version 1.27 after the community support period ends** as long as your cluster has LTS enabled.

->

For above as per my understanding, we are not able to create new AKS cluster with version 1.27 after the community support period ends.

Could you please kindly confirm and update the same.

### Page URL

https://learn.microsoft.com/ja-jp/azure/aks/long-term-support?source=docs

### Content source URL

https://github.com/MicrosoftDocs/azure-aks-docs/blob/main/articles/aks/long-term-support.md

### Author

@justindavies

### Document Id

1bc57bf7-15d8-4381-2f36-89789e50bbc0

**Comment by schaffererin** [comment]
#assign:schaffererin

**Comment by schaffererin** [comment]
As we've not heard back, I'm going to close out this issue. #please-close
