### ISSUE TITLE
AKS Learn feedback:

### ISSUE THREAD

**Issue by BertonLan** [MicrosoftDocs/azure-aks-docs#49]
### Type of issue

Typo

### Feedback

Test

### Page URL

https://learn.microsoft.com/en-us/azure/aks/learn/quick-windows-container-deploy-portal?tabs=azure-cli

### Content source URL

https://github.com/MicrosoftDocs/azure-aks-docs/blob/main/articles/aks/learn/quick-windows-container-deploy-portal.md

### Author

@schaffererin

### Document Id

4f23e28d-94e6-160a-ec4f-590d22ca167a

**Comment by schaffererin** [comment]
Hi, @BertonLan, I'm not seeing any information in this issue that outlines where the typo is. Could you please provide a bit more information so I can get this resolved?

**Comment by schaffererin** [comment]
As we've not received follow up on this issue, we're going to close it out. Please feel free to open up a new GitHub issue if you run into any documentation-related issues in the future. Thank you. #please-close
