### ISSUE TITLE
AKS Learn feedback: Unable to download sample image

### ISSUE THREAD

**Issue by vinomanoharan** [MicrosoftDocs/azure-aks-docs#50]
### Type of issue

Outdated article

### Feedback

I am trying to setup a nginx using this link, but I could not download this image. 
mcr.microsoft.com/azuredocs/aks-helloworld:v1

Do you have an equivalent or new image for this?

### Page URL

https://learn.microsoft.com/en-us/azure/aks/create-nginx-ingress-private-controller

### Content source URL

https://github.com/MicrosoftDocs/azure-aks-docs/blob/main/articles/aks/create-nginx-ingress-private-controller.md

### Author

@sabbour

### Document Id

efc7cb21-2280-8c0e-7f25-e913e705729d

**Comment by schaffererin** [comment]
#assign:schaffererin

**Comment by schaffererin** [comment]
Hi @vinomanoharan, this article has been updated and no longer references this image. I'm going to close out this GitHub issue. Thanks for providing your feedback! #please-close
