### ISSUE TITLE
AKS Learn feedback: image mcr.microsoft.com/azuredocs/azure-vote-front is not found

### ISSUE THREAD

**Issue by pradipd** [MicrosoftDocs/azure-aks-docs#55]
### Type of issue

Code doesn't work

### Feedback

The image mcr.microsoft.com/azuredocs/azure-vote-front:v1 does not exist in mcr.microsoft.com.

docker pull mcr.microsoft.com/azuredocs/azure-vote-front:v1 
Error response from daemon: manifest for mcr.microsoft.com/azuredocs/azure-vote-front:v1 not found: manifest unknown: manifest tagged by "v1" is not found

### Page URL

https://learn.microsoft.com/en-us/azure/aks/tutorial-kubernetes-app-update?tabs=azure-cli

### Content source URL

https://github.com/MicrosoftDocs/azure-aks-docs/blob/main/articles/aks/tutorial-kubernetes-app-update.md

### Author

@schaffererin

### Document Id

0d838315-ae22-17f9-2fce-f735a85d78e0

**Comment by schaffererin** [comment]
#assign:schaffererin

**Comment by schaffererin** [comment]
Hi, @pradipd! Thank you for opening up this issue.

This was an old tutorial that was removed from our table of contents but wasn't fully removed from the documentation as it should've been. I opened up a PR to remove it from the site. If you're interested, please see https://learn.microsoft.com/en-us/azure/aks/tutorial-kubernetes-prepare-app?tabs=azure-cli to review our updated tutorial series.

I'm going to close out this GitHub issue now. Thanks again!

#please-close
