### ISSUE TITLE
Managed NGINX ingress with the application routing add-on - not working

### ISSUE THREAD

**Issue by junglebrain** [MicrosoftDocs/azure-aks-docs#65]
### Type of issue

Code doesn't work

### Feedback

The step `kubectl apply -f ingress.yaml -n aks-store` does not work. I get the following error:

```Error from server (InternalError): error when creating "ingress.yaml": Internal error occurred: failed calling webhook "validate.nginx.ingress.kubernetes.io": failed to call webhook: Post "https://nginx-ingress-ingress-nginx-controller-admission.default.svc:443/networking/v1/ingresses?timeout=10s": service "nginx-ingress-ingress-nginx-controller-admission" not found```

### Page URL

https://learn.microsoft.com/en-us/azure/aks/app-routing

### Content source URL

https://github.com/MicrosoftDocs/azure-aks-docs/blob/main/articles/aks/app-routing.md

### Author

@asudbring

### Document Id

6cfdc0c8-1b03-2c70-2a3a-ab0935872cc0

**Comment by schaffererin** [comment]
#assign:schaffererin

**Comment by schaffererin** [comment]
Hi, @junglebrain. Thank you for your feedback. I ran through testing of the deployment and experienced no issues. That said, it appears that no documentation updates are needed here and that the issue might be on the user side. I'm going to close out this GitHub issue. If you run into any documentation errors in the future, please feel free to open up a new one. Thanks again! #please-close
