### ISSUE TITLE
Linking to archived repo

### ISSUE THREAD

**Issue by kszicsillag** [MicrosoftDocs/azure-aks-docs#68]
### Type of issue

Outdated article

### Feedback

The [Check out the Autoscale sample for virtual nodes](https://github.com/Azure-Samples/virtual-node-autoscale) link in the *Next steps* section points to an archived GitHub repo.

### Page URL

https://learn.microsoft.com/en-us/azure/aks/virtual-nodes

### Content source URL

https://github.com/MicrosoftDocs/azure-aks-docs/blob/main/articles/aks/virtual-nodes.md

### Author

@schaffererin

### Document Id

e2975b46-0121-62fa-756f-5bed2d3b6c21

**Comment by schaffererin** [comment]
Hi, @kszicsillag! Thank you for your feedback. I merged a PR that removes the link to the archived repo from the article. The updates to the doc will be live in the AKS documentation shortly. I'm now going to close out this PR. If you have any additional feedback about the AKS documentation, please feel free to open a new issue. #please-close
