### ISSUE TITLE
AKS Learn feedback: Multi-instance GPU documentation is out of date

### ISSUE THREAD

**Issue by SatyKrish** [MicrosoftDocs/azure-aks-docs#69]
### Type of issue

Typo

### Feedback

Nvidia GitHub repos listed under `Install the NVIDIA device plugin and GPU feature discovery` section are not found. 

Nvidia GPU feature discovery project is archived and merged in Nvidia Device Plugin.

Please update the document to work with current features.

### Page URL

https://learn.microsoft.com/en-us/azure/aks/gpu-multi-instance?tabs=azure-cli

### Content source URL

https://github.com/MicrosoftDocs/azure-aks-docs/blob/main/articles/aks/gpu-multi-instance.md

### Author

@schaffererin

### Document Id

5ec41d1a-14bc-af33-69ae-a0984de965b8

**Comment by schaffererin** [comment]
Hi, @SatyKrish. Thank you for your feedback. I apologize for the delay in response. The article has been updated, so I will close out this GitHub issue.

#please-close
