### ISSUE TITLE
AKS Learn feedback: Inconsistent flag for ignore ignore-daemonset-utilization

### ISSUE THREAD

**Issue by mikaelweave** [MicrosoftDocs/azure-aks-docs#74]
### Type of issue

Typo

### Feedback

On [this page](https://learn.microsoft.com/en-us/azure/aks/cluster-autoscaler-overview) the flag is `ignore-daemonset-utilization`. On [this page](https://learn.microsoft.com/en-us/azure/aks/cluster-autoscaler?tabs=azure-cli) it's `ignore-daemonsets-utilization`. Note how `daemonset` is plural on one doc and singular on the other.

### Page URL

https://learn.microsoft.com/en-us/azure/aks/cluster-autoscaler-overview

### Content source URL

https://github.com/MicrosoftDocs/azure-aks-docs/blob/main/articles/aks/cluster-autoscaler-overview.md

### Author

@schaffererin

### Document Id

d72c23ae-9769-3264-895f-243840ef4b0e

**Comment by schaffererin** [comment]
Hi, @mikaelweave. Thank you for your feedback. I merged a PR that fixes the incorrect parameter in the [Cluster autoscaling in Azure Kubernetes Service (AKS) overview](https://learn.microsoft.com/en-us/azure/aks/cluster-autoscaler-overview). The update to the doc will be live in the AKS documentation shortly. I'm now going to close out this PR. If you have any additional feedback about the AKS documentation, please feel free to open a new issue. #please-close
