### ISSUE TITLE
AKS Learn feedback:

### ISSUE THREAD

**Issue by csanchez83** [MicrosoftDocs/azure-aks-docs#90]
### Type of issue

Typo

### Feedback

Modify file .yaml

### Page URL

https://learn.microsoft.com/es-mx/azure/aks/tutorial-kubernetes-paas-services?tabs=azure-cli

### Content source URL

https://github.com/MicrosoftDocs/azure-aks-docs/blob/main/articles/aks/tutorial-kubernetes-paas-services.md

### Author

@schaffererin

### Document Id

f8e55f97-dea3-809d-d353-dac4e6e8be7c

**Comment by schaffererin** [comment]
Hi, @csanchez83, can you please elaborate on the issue?

**Comment by schaffererin** [comment]
As we've not heard back, I'm going to close out this issue. #please-close
