### ISSUE TITLE
AKS Learn feedback: typo in documentation of seccomp

### ISSUE THREAD

**Issue by cengelenVW** [MicrosoftDocs/azure-aks-docs#93]
### Type of issue

Typo

### Feedback

in the first sentence of https://learn.microsoft.com/en-us/azure/aks/secure-container-access#restrict-your-containers-system-calls-with-seccomp there is a typo: `"seccompDefualt"`. This should be `"seccompDefault"`

### Page URL

https://learn.microsoft.com/en-us/azure/aks/secure-container-access

### Content source URL

https://github.com/MicrosoftDocs/azure-aks-docs/blob/main/articles/aks/secure-container-access.md

### Author

@allyford

### Document Id

02a59227-3bf6-1f25-0b46-16f9d5057b50

**Comment by schaffererin** [comment]
#assign:schaffererin

**Comment by schaffererin** [comment]
Hi, @cengelenVW, thank you for your feedback. Good catch.

We've merged a [PR](https://github.com/MicrosoftDocs/azure-aks-docs-pr/pull/611) to correct the issue, and the changes will be live in the AKS documentation shortly. I will now close out this issue.

#please-close
