### ISSUE TITLE
AKS Learn feedback: Link to Documentation is outdated and not working

### ISSUE THREAD

**Issue by SullzCode** [MicrosoftDocs/azure-aks-docs#94]
### Type of issue

Missing information

### Feedback

The link below found on AKS page for generating SSH key is not working
 Create an AzAPI resource to generate an SSH key pair using [azapi_resource_action](https://registry.terraform.io/providers/Azure/azapi/latest/docs/resources/azapi_resource_action) 
![image](https://github.com/user-attachments/assets/d7904f49-5e10-43e0-aed9-7571478a6849)
![terraform](https://github.com/user-attachments/assets/9f64da1e-65b3-4de4-9270-5d8e6c2a9963)

### Page URL

https://learn.microsoft.com/en-us/azure/aks/learn/quick-kubernetes-deploy-terraform

### Content source URL

https://github.com/MicrosoftDocs/azure-aks-docs/blob/main/articles/aks/learn/quick-kubernetes-deploy-terraform.md

### Author

@schaffererin

### Document Id

dff8fa9c-b5e2-c368-cb36-de9e304ecb80

**Comment by schaffererin** [comment]
#assign:schaffererin

**Comment by schaffererin** [comment]
@SullzCode, thanks for bringing this to our attention! I fixed the broken link and the [changes were merged](https://github.com/MicrosoftDocs/azure-aks-docs-pr/pull/605). The public-facing article will reflect those changes shortly. I'm going to close out this issue now. Thanks again!

#please-close
